# handlers file
---
- name: restart nfs-server
  ansible.builtin.service:
    name: "{{ nfs_server_service_name }}"
    state: restarted
  when: service_default_state | default('started') == 'started'
